spring:
  data:
    mongodb:
      host: localhost
      database: admin
      port: 27017
      username: admin
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
server:
  port: 9212
  tomcat:
    uri-encoding: UTF-8