spring:
  application:
    name: spring-boot-admin-server
#eureka:
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 10
#  client:
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
server:
  port: 9101